# First of all we will go to the travis-ci and will activate this repo of github from settings
# after activating this repo of github from travis-ci
# whenever we push the code into github -- it will go to travis-ci too

sudo: required

language: generic

services:
  - docker

#! Tests
before_install:
  - docker build -t zohaibbutt/vidly-react-tests -f ./client/Dockerfile.dev ./client
  # - docker build -t zohaibbutt/vidly-express-tests -f ./server/Dockerfile.dev ./server
  # express tests are not passing from now, 1st i have to pass all the tests in development mode
script:
  - docker run -e CI=true zohaibbutt/vidly-react-tests yarn test
  # - docker run -e CI=true zohaibbutt/vidly-express-tests yarn test

#! Push All The Code in to Docker Hub
after_success:
  # building all the services
  #? !!!!!!!!!!!!!tagging must be in standard userID/someName as we wanna push them into docker hub with our ID
  - docker build -t 03004968719/vidly-client ./client
  - docker build -t 03004968719/vidly-nginx ./nginx
  - docker build -t 03004968719/vidly-server ./server

  # Log in to docker CLI
  #   We will now go to the travis-ci/thisRepo/moreOptions and we will add env variables for our docker id and username
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin

  # Take those images and push them to docker hub with their new tags
  - docker push 03004968719/vidly-client
  - docker push 03004968719/vidly-nginx
  - docker push 03004968719/vidly-server
