apiVersion: extensions/v1beta1 # this apiVersion is expired but this is the only one working in cloud
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 # rewriting target
spec:
  rules:
    - http:
        paths:
          - path: / # this must be in same format -- simple route
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /graphql
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 4000
